export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const ITEM_LOADING = "ITEM_LOADING";

export const GET_CUSTOMER_ITEMS = "GET_CUSTOMER_ITEMS";
export const ADD_CUSTOMER_ITEMS = "ADD_CUSTOMER_ITEMS";
export const DELETE_CUSTOMER_ITEMS = "DELETE_CUSTOMER_ITEMS";
